---

version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - db

  php:
    image: php:fpm
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      YSQL_DATABASE: baza
      MYSQL_USER: robot
      MYSQL_PASSWORD: 987654321
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
